# Generated by Django 4.2.7 on 2024-05-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram.', unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя в Telegram.', max_length=120, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя в Telegram.', max_length=120, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан пользователь.', verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.telegramuser'),
        ),
    ]
